### ISSUE TITLE
Bibl Module TEI titleStmt Change

### ISSUE THREAD

**Issue by davidamichelson** [srophe/caesarea#110]
@wlpotter @nathangibson @dlschwartz

So we have had a long running confusing issue with how our Bibl module represents its entries. It is sort of a version of the "is the URI the document" conundrum: https://www.w3.org/DesignIssues/HTTP-URI.html

The issue is that our TEI documents for citations have the same "title" as the citation itself. This produces some confusion for example, see this record:

http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/bibl/EDLHK9C5

This is a TEI file about this citation:  Solin, Heiki. “Analecta Epigraphica.” _Arctos_ 6 (1969): 101–12.

The title of the citation is Analecta epigraphica and the author of the citation is Heiki Solin.

The title of the TEI document about the citation is also Analecta epigraphica but the authors of the TEI document about the citation are Joe Rife and Will Potter.

This creates some confusion in the attribution of the TEI file where you get:
```Joseph Rife, entry contributor, “Analecta epigraphica” ```

We have worried rightly in the past that this might be confused as claiming credit for the cited work. At the very least it is confusing as a citation.

So, I would like to propose the following change in how the bibl Module for Syriaca.org, Caesarea-Maritima, and Srophe App in general handles the TEI:titleStmt for TEI records about citations (Nathan you need not adopt this if you do not want to of course for Biblical Arabica).

We would change the TEI:titleStmt to be: Citation Title + (Author[s] Last, Year)

So in this case the TEI record would have the following TEI:titleStmt/title in the header:
```Analecta Epigraphica (Solin 1969)```

This same ```Analecta Epigraphica (Solin 1969)``` would appear at the top of the HTML page and in the Browse and Search Results

And the TEI attribution would be 
Joseph Rife, entry contributor, “Analecta Epigraphica (Solin 1969)"

**Comment by davidamichelson** [comment]
Please vote here 
/polls Yes 'No' "Maybe"

**Comment by wlpotter** [comment]
This seems like a reasonable change. A few cases we may need to account for:

1. Different authors with the same last name. Will we add the first initial of each author to disambiguate (this is what CMOS author-date format recommends)? I don't think we need to disambiguate in the similar case of multiple publications in a year (e.g. 1998a, 1998b, etc.) as we will have the publication title right there.

2. Will we have a cut-off for switching from a serial list of authors to "et al."? I believe CMOS recommends four or more authors being list with "et al.". 

3. For roles other than author, will we use role designations (e.g., "ed.")? I'm not sure if CMOS author-date specifies this or not. It may be unnecessary since the full citation follows both in the browse preview and on the HTML page itself (a fact which may also determine how we handle the first case).

**Comment by davidamichelson** [comment]
Thanks @wlpotter I miss you! 

I think that 1 and 3 are moot because the citation title is always present thus the need to disambiguate names or years is not needed.

For 2 I think we use up to three surnames and then just one name and et al.

**Comment by dlschwartz** [comment]
I have no objections

**Comment by nathangibson** [comment]
Sounds good!
