### ISSUE TITLE
Add language for reuse of text and CC-BY language to each record

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#302]

**Comment by davidamichelson** [comment]
“Except where noted, this entry is copyright 2021 by the contributors (Joe Rife, et al.) and licensed under the Attribution 4.0 International (CC BY 4.0) license. 
(Note that some may be in the public domain). Some texts quoted in this entry have copyright restrictions and are reused under Section 107 of the Copyright Act of 1976 which permits “fair use” for purposes such as criticism, comment, scholarship, and research. These texts remain under copyright of their owners. No copyright infringement is intended.”

Provide a contact for the copyright holder.

**Comment by davidamichelson** [comment]
```
<p>
Except for materials quoted from other sources, this entry is copyright 2021 by the contributors (Joe Rife, et al.) and licensed under the Attribution 4.0 International (CC BY 4.0) license.
</p>
<p>
Some texts quoted in this entry may be in the public domain in the United States. No copyright is asserted for these quotations. 
</p>
<p>
Some texts quoted in this entry may have copyright restrictions and are reused under Section 107 of the Copyright Act of 1976 (Title 17 of the United States Code) which permits “fair use” of copyrighted materials for purposes such as criticism, comment, scholarship, and research. These texts remain under copyright of their owners. No copyright infringement is intended.
</p>
```

**Comment by davidamichelson** [comment]
@wsalesky Could you please change the Copyright and License for Reuse section of the Testimonia HTML individual record pages.

Right now I think that textnode of /TEI/teiHeader/fileDesc/publicationStmt/availability/licence/p displays at the bottom of How to Cite This Entry expanded section in the HTML as "Distributed under a Creative Commons Attribution 4.0 Unported License." We are going to change this textnode contents, but please keep the display of that path working the same way.

I think that you are hard coding in: "Except where otherwise noted, this page is © Caesarea City and Port Exploration Project 2020." Please remove that and we will add that into the licence/p textnode as an additional p instead.

Please note that we will now have multi p elements to display.

We would like you to change their location. Please put it above and outside the How to Cite box so that it always displays on every record page for Testimonia.

**Comment by wsalesky** [comment]
Done

**Comment by davidamichelson** [comment]
Great! I will test tomorrow and close if it works.

**Comment by wsalesky** [comment]
@davidamichelson can this be closed?

**Comment by davidamichelson** [comment]
Great work!
