### ISSUE TITLE
Linked data box on Testimonia records

### ISSUE THREAD

**Issue by wlpotter** [srophe/caesarea#47]
We would like to add a linked data box to the testimonia records.

Details to follow.

**Comment by davidamichelson** [comment]
@wsalesky Please create a box under the "About This Text" box and label it "Linked Data".

The box should the have the following prose:

This record has 7 [calculated number based on URIs collected in the record] connections.
Rome (from Place Composed URI)
Ammianus Marcellinus (from Author URI)
History (from Title URI if available)
Bibliography (I want to link to the 4 bibl items, but am not sure how to do it)

Please just make the empty box for now as a place holder for Friday and we can discuss further.

**Comment by wsalesky** [comment]
Added. 
@wlpotter @davidamichelson please review.

**Comment by davidamichelson** [comment]
@wsalesky 

Okay, we are ready to make the box do things :)

To save on time loading the page the box should just populate as it currently does, but when you click on a link it should be a RESTful API URL which then loads a new page with the results.

Here is an mock up based on:
http://wwwb.library.vanderbilt.edu/exist/apps/caesarea/testimonia/2#bib2-1

(Click edit to view the markdown)

----
Linked Data (?)
----
7 entities in this record have connections to external resources.

**Data**
- Rome
  - [Pleiades Gazetteer Entry](https://pleiades.stoa.org/places/423025)
  - [Search Peripleo Linked Data](http://peripleo.pelagios.org/ui#selected=https://pleiades.stoa.org/places/423025)

- Flavius Josephus
  - [VIAF Entry](http://viaf.org/viaf/22143666)
  - [Search WorldCat Identities](http://worldcat.org/identities) NB: Need API Link

- Antiquities of the Jews
  - [Perseus Electronic Text](http://data.perseus.org/citations/urn:cts:greekLit:tlg0526.tlg001.perseus-grc1:14.76 )

**Bibliography**
-  [Flavius Josephus, _Antiquitates Judaicae: Machine Readable Text_](https://caesarea-maritima.org/bibl/DJ9R4TA9)
-  [Flavius Josephus, _Antiquities of the Jews: Machine Readable Text_](https://caesarea-maritima.org/bibl/KULZ5FJB)
-  [Flavius Josephus, _Antiquitates Judaicae_](https://caesarea-maritima.org/bibl/IYCZFI7G)
-  [Flavius Josephus, _Antiquities of the Jews_](https://caesarea-maritima.org/bibl/8WGC55QX)

----

Notes:

Places:
Please have a script that finds any @ref="https://pleiades.stoa.org/places..." in the TEI file for the record and does the following:

1) Provides a direct URL link to Pleiades
2) Constructs a RESTful search URL of Peripleo based on the pelagios ID:
e.g. http://peripleo.pelagios.org/ui#selected=https://pleiades.stoa.org/places/423025

Persons:
Please have a script that finds any @ref="http://viaf.org/viaf/..." in the TEI file for the record and does the following:

1) Provides a direct URL link to VIAF
2) Constructs a search of WorldCat Identities, WorldCat Entities or another WorldCat Linked Data API using the VIAF URI
Note: We could not figure out access to the WorldCat Linked Date, Indentities or Entities, maybe you will have better luck with http://worldcat.org/identities ?

Bibliography:
Since the Bibl module has its own linked data box it seems silly to replicate it here. So please just link to any TEI:ptr/@target in TEI:text/body/listBibl/bibl. Please construct the visible portion of the link with both TEI:author and TEI:title

Lastly, please note that we have decided not to include any mention of The New Encyclopedia of Archaeological Excavations in the Holy Land as a bibl because it will occur in every record, so please exclude the TEI:ptr/@target found in //TEI taxonomy

**Comment by davidamichelson** [comment]
- [ ] @wlpotter Please research how to use CTS URNS

- [ ] @wsalesky Please research how to use the WorldCat Identities, WorldCat Entities or other WorldCat Linked Data APIs

**Comment by davidamichelson** [comment]
One more thought, @wsalesky You could add the tiny logos for each item in the box like we do for Bibliography module.

**Comment by wlpotter** [comment]
I've made an issue in data, [here](https://github.com/srophe/caesarea-data/issues/27) about the changes needed to the `tei:bibl`s in the testimonia records which will facilitate linking out to the texts.

Those changes will facilitate the construction of the links to Perseus, etc. via URN.

**Comment by wsalesky** [comment]
@davidamichelson @wlpotter Done, except the icons.

**Comment by davidamichelson** [comment]
@wsalesky Last issue here, in the Testimonia Record Page Linked Data Box please make two fixes:

1. Please have the bibliography items point to the Zotero URIS rather than the Caesarea-Maritima.org/bibl URIS
2. Please have the count (This record has X connections) update to reflect this number.

Thanks!

**Comment by wsalesky** [comment]
1. Fixed
2. already represents the # of connections.
